FROM nginx:1.21.1
WORKDIR /app
COPY package.json ./
RUN apt update
RUN apt install -y npm
RUN npm i -g pm2
COPY ./package.json ./package.json
RUN npm i
COPY . ./
COPY ./scripts/start-nginx.sh ./start.
RUN npm run build
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./ssl /etc/ssl
COPY ./scripts/start-nginx.sh ./start
RUN rm -rf /etc/nginx/conf.d/default.conf
CMD ["bash", "./start"]
EXPOSE 80
EXPOSE 443
